// Test generated by RoostGPT for test learn-springboot using AI Type Open AI and AI Model gpt-4

package com.didispace.chapter11;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class HelloController_index_b1e8101632_Test {

    @MockBean
    private HelloController helloController;

    @Test
    public void testIndexSuccess() {
        Mockito.when(helloController.index()).thenReturn("Hello World");
        String result = helloController.index();
        Assertions.assertEquals("Hello World", result, "Expected and actual results do not match");
    }

    @Test
    public void testIndexFailure() {
        Mockito.when(helloController.index()).thenReturn("Hello World");
        String result = helloController.index();
        Assertions.assertNotEquals("Hello Mars", result, "Expected and actual results should not match");
    }
}
